# Generated by Django 5.1.5 on 2025-01-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0003_learndb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='learndb',
            new_name='NewReg',
        ),
    ]
