# Generated by Django 5.1.5 on 2025-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0004_rename_learndb_newreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='pkadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packname', models.CharField(max_length=50)),
                ('packprice', models.IntegerField()),
                ('packdesc', models.TextField()),
                ('packimg', models.ImageField(upload_to='pics')),
                ('cancel', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('guide', models.CharField(max_length=50)),
                ('groupsize', models.IntegerField()),
            ],
        ),
    ]
