# Generated by Django 5.1.5 on 2025-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0005_pkadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkadmin',
            name='packdesc',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='pkadmin',
            name='packimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
