# Generated by Django 5.1.5 on 2025-01-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0006_alter_pkadmin_packdesc_alter_pkadmin_packimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkadmin',
            name='packimg',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
