# Generated by Django 5.1.5 on 2025-01-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0009_updatepass_newpassword_alter_pkadmin_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
