# Generated by Django 5.1.5 on 2025-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0010_forgotpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='inotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpdb', models.IntegerField()),
            ],
        ),
    ]
