# Generated by Django 5.1.5 on 2025-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0011_inotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='newpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpass', models.CharField(max_length=50)),
            ],
        ),
    ]
