# Generated by Django 5.1.5 on 2025-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_furnituredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredetails',
            name='productid',
            field=models.IntegerField(unique=True),
        ),
    ]
