# Generated by Django 5.1.5 on 2025-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_furnituredetails_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituredetails',
            name='productid',
            field=models.IntegerField(unique=True),
        ),
    ]
