# Generated by Django 5.1.5 on 2025-02-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_furnituredetails_productdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituredetails',
            name='productstock',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='signup',
            name='dateofbirth',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='signup',
            name='fullname',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='postcode',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default='0')),
                ('finalprice', models.IntegerField(default='0')),
                ('customers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.signup')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.furnituredetails')),
            ],
        ),
    ]
