# Generated by Django 3.1.12 on 2025-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20250206_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
