# Generated by Django 3.1.12 on 2025-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20250206_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dateofbirth',
            field=models.DateField(default='0'),
        ),
    ]
