# Generated by Django 3.1.12 on 2025-02-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20250206_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dateofbirth',
            field=models.DateField(default='dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='postcode',
            field=models.IntegerField(default='000000'),
        ),
    ]
