# Generated by Django 3.1.12 on 2025-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_auto_20250207_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
