# Generated by Django 3.1.12 on 2025-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituredetails',
            name='product_pay',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
